# Automatically generated by reggae version 0.5.3+
# Do not edit by hand
all: example_test ut
.SUFFIXES:
CC = clang
CXX = clang++
DC = dmd
objs/example_test.objs/example/test/mock_network.o: example/test/mock_network.cpp Makefile
	$(CXX) -Wall -Werror -Wextra -g -std=c++14 -I. -Iexample/test -Iexample/src -Iexample/deps -MMD -MT objs/example_test.objs/example/test/mock_network.o -MF objs/example_test.objs/example/test/mock_network.o.dep -o objs/example_test.objs/example/test/mock_network.o -c example/test/mock_network.cpp
	@cp objs/example_test.objs/example/test/mock_network.o.dep objs/example_test.objs/example/test/mock_network.o.dep.P; \
    sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\$$//' \
        -e '/^$$/ d' -e 's/$$/ :/' < objs/example_test.objs/example/test/mock_network.o.dep >> objs/example_test.objs/example/test/mock_network.o.dep.P; \
    rm -f objs/example_test.objs/example/test/mock_network.o.dep

-include objs/example_test.objs/example/test/mock_network.o.dep.P


objs/example_test.objs/example/test/mock_other.o: example/test/mock_other.cpp Makefile
	$(CXX) -Wall -Werror -Wextra -g -std=c++14 -I. -Iexample/test -Iexample/src -Iexample/deps -MMD -MT objs/example_test.objs/example/test/mock_other.o -MF objs/example_test.objs/example/test/mock_other.o.dep -o objs/example_test.objs/example/test/mock_other.o -c example/test/mock_other.cpp
	@cp objs/example_test.objs/example/test/mock_other.o.dep objs/example_test.objs/example/test/mock_other.o.dep.P; \
    sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\$$//' \
        -e '/^$$/ d' -e 's/$$/ :/' < objs/example_test.objs/example/test/mock_other.o.dep >> objs/example_test.objs/example/test/mock_other.o.dep.P; \
    rm -f objs/example_test.objs/example/test/mock_other.o.dep

-include objs/example_test.objs/example/test/mock_other.o.dep.P


objs/example_test.objs/example/test/test.o: example/test/test.cpp Makefile
	$(CXX) -Wall -Werror -Wextra -g -std=c++14 -I. -Iexample/test -Iexample/src -Iexample/deps -MMD -MT objs/example_test.objs/example/test/test.o -MF objs/example_test.objs/example/test/test.o.dep -o objs/example_test.objs/example/test/test.o -c example/test/test.cpp
	@cp objs/example_test.objs/example/test/test.o.dep objs/example_test.objs/example/test/test.o.dep.P; \
    sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\$$//' \
        -e '/^$$/ d' -e 's/$$/ :/' < objs/example_test.objs/example/test/test.o.dep >> objs/example_test.objs/example/test/test.o.dep.P; \
    rm -f objs/example_test.objs/example/test/test.o.dep

-include objs/example_test.objs/example/test/test.o.dep.P


objs/example_test.objs/example/test/mock_cpp.o: example/test/mock_cpp.cpp Makefile
	$(CXX) -Wall -Werror -Wextra -g -std=c++14 -I. -Iexample/test -Iexample/src -Iexample/deps -MMD -MT objs/example_test.objs/example/test/mock_cpp.o -MF objs/example_test.objs/example/test/mock_cpp.o.dep -o objs/example_test.objs/example/test/mock_cpp.o -c example/test/mock_cpp.cpp
	@cp objs/example_test.objs/example/test/mock_cpp.o.dep objs/example_test.objs/example/test/mock_cpp.o.dep.P; \
    sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\$$//' \
        -e '/^$$/ d' -e 's/$$/ :/' < objs/example_test.objs/example/test/mock_cpp.o.dep >> objs/example_test.objs/example/test/mock_cpp.o.dep.P; \
    rm -f objs/example_test.objs/example/test/mock_cpp.o.dep

-include objs/example_test.objs/example/test/mock_cpp.o.dep.P


objs/example_test.objs/example/src/cpp_prod.o: example/src/cpp_prod.cpp Makefile
	$(CXX) -Wall -Werror -Wextra -g -include mocks.h -I. -Iexample/test -Iexample/src -Iexample/deps -MMD -MT objs/example_test.objs/example/src/cpp_prod.o -MF objs/example_test.objs/example/src/cpp_prod.o.dep -o objs/example_test.objs/example/src/cpp_prod.o -c example/src/cpp_prod.cpp
	@cp objs/example_test.objs/example/src/cpp_prod.o.dep objs/example_test.objs/example/src/cpp_prod.o.dep.P; \
    sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\$$//' \
        -e '/^$$/ d' -e 's/$$/ :/' < objs/example_test.objs/example/src/cpp_prod.o.dep >> objs/example_test.objs/example/src/cpp_prod.o.dep.P; \
    rm -f objs/example_test.objs/example/src/cpp_prod.o.dep

-include objs/example_test.objs/example/src/cpp_prod.o.dep.P


objs/example_test.objs/example/src/prod.o: example/src/prod.c Makefile
	$(CC) -Wall -Werror -Wextra -g -include mocks.h -I. -Iexample/test -Iexample/src -Iexample/deps -MMD -MT objs/example_test.objs/example/src/prod.o -MF objs/example_test.objs/example/src/prod.o.dep -o objs/example_test.objs/example/src/prod.o -c example/src/prod.c
	@cp objs/example_test.objs/example/src/prod.o.dep objs/example_test.objs/example/src/prod.o.dep.P; \
    sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\$$//' \
        -e '/^$$/ d' -e 's/$$/ :/' < objs/example_test.objs/example/src/prod.o.dep >> objs/example_test.objs/example/src/prod.o.dep.P; \
    rm -f objs/example_test.objs/example/src/prod.o.dep

-include objs/example_test.objs/example/src/prod.o.dep.P


objs/example_test.objs/example/deps/other.o: example/deps/other.c Makefile
	$(CC) -Wall -Werror -Wextra -g  -MMD -MT objs/example_test.objs/example/deps/other.o -MF objs/example_test.objs/example/deps/other.o.dep -o objs/example_test.objs/example/deps/other.o -c example/deps/other.c
	@cp objs/example_test.objs/example/deps/other.o.dep objs/example_test.objs/example/deps/other.o.dep.P; \
    sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\$$//' \
        -e '/^$$/ d' -e 's/$$/ :/' < objs/example_test.objs/example/deps/other.o.dep >> objs/example_test.objs/example/deps/other.o.dep.P; \
    rm -f objs/example_test.objs/example/deps/other.o.dep

-include objs/example_test.objs/example/deps/other.o.dep.P


objs/example_test.objs/example/deps/cpp_other.o: example/deps/cpp_other.cpp Makefile
	$(CXX) -Wall -Werror -Wextra -g  -MMD -MT objs/example_test.objs/example/deps/cpp_other.o -MF objs/example_test.objs/example/deps/cpp_other.o.dep -o objs/example_test.objs/example/deps/cpp_other.o -c example/deps/cpp_other.cpp
	@cp objs/example_test.objs/example/deps/cpp_other.o.dep objs/example_test.objs/example/deps/cpp_other.o.dep.P; \
    sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\$$//' \
        -e '/^$$/ d' -e 's/$$/ :/' < objs/example_test.objs/example/deps/cpp_other.o.dep >> objs/example_test.objs/example/deps/cpp_other.o.dep.P; \
    rm -f objs/example_test.objs/example/deps/cpp_other.o.dep

-include objs/example_test.objs/example/deps/cpp_other.o.dep.P


example_test: objs/example_test.objs/example/test/mock_network.o objs/example_test.objs/example/test/mock_other.o objs/example_test.objs/example/test/test.o objs/example_test.objs/example/test/mock_cpp.o objs/example_test.objs/example/src/cpp_prod.o objs/example_test.objs/example/src/prod.o objs/example_test.objs/example/deps/other.o objs/example_test.objs/example/deps/cpp_other.o Makefile
	$(CXX) -o example_test  objs/example_test.objs/example/test/mock_network.o objs/example_test.objs/example/test/mock_other.o objs/example_test.objs/example/test/test.o objs/example_test.objs/example/test/mock_cpp.o objs/example_test.objs/example/src/cpp_prod.o objs/example_test.objs/example/src/prod.o objs/example_test.objs/example/deps/other.o objs/example_test.objs/example/deps/cpp_other.o
objs/ut.objs/tests/main.o: tests/main.cpp Makefile
	$(CXX) -Wall -Werror -Wextra -g -std=c++14 -I. -Itests -MMD -MT objs/ut.objs/tests/main.o -MF objs/ut.objs/tests/main.o.dep -o objs/ut.objs/tests/main.o -c tests/main.cpp
	@cp objs/ut.objs/tests/main.o.dep objs/ut.objs/tests/main.o.dep.P; \
    sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\$$//' \
        -e '/^$$/ d' -e 's/$$/ :/' < objs/ut.objs/tests/main.o.dep >> objs/ut.objs/tests/main.o.dep.P; \
    rm -f objs/ut.objs/tests/main.o.dep

-include objs/ut.objs/tests/main.o.dep.P


objs/ut.objs/tests/test_mock_scope.o: tests/test_mock_scope.cpp Makefile
	$(CXX) -Wall -Werror -Wextra -g -std=c++14 -I. -Itests -MMD -MT objs/ut.objs/tests/test_mock_scope.o -MF objs/ut.objs/tests/test_mock_scope.o.dep -o objs/ut.objs/tests/test_mock_scope.o -c tests/test_mock_scope.cpp
	@cp objs/ut.objs/tests/test_mock_scope.o.dep objs/ut.objs/tests/test_mock_scope.o.dep.P; \
    sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\$$//' \
        -e '/^$$/ d' -e 's/$$/ :/' < objs/ut.objs/tests/test_mock_scope.o.dep >> objs/ut.objs/tests/test_mock_scope.o.dep.P; \
    rm -f objs/ut.objs/tests/test_mock_scope.o.dep

-include objs/ut.objs/tests/test_mock_scope.o.dep.P


objs/ut.objs/tests/test_traits.o: tests/test_traits.cpp Makefile
	$(CXX) -Wall -Werror -Wextra -g -std=c++14 -I. -Itests -MMD -MT objs/ut.objs/tests/test_traits.o -MF objs/ut.objs/tests/test_traits.o.dep -o objs/ut.objs/tests/test_traits.o -c tests/test_traits.cpp
	@cp objs/ut.objs/tests/test_traits.o.dep objs/ut.objs/tests/test_traits.o.dep.P; \
    sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\$$//' \
        -e '/^$$/ d' -e 's/$$/ :/' < objs/ut.objs/tests/test_traits.o.dep >> objs/ut.objs/tests/test_traits.o.dep.P; \
    rm -f objs/ut.objs/tests/test_traits.o.dep

-include objs/ut.objs/tests/test_traits.o.dep.P


objs/ut.objs/tests/test_exceptions.o: tests/test_exceptions.cpp Makefile
	$(CXX) -Wall -Werror -Wextra -g -std=c++14 -I. -Itests -MMD -MT objs/ut.objs/tests/test_exceptions.o -MF objs/ut.objs/tests/test_exceptions.o.dep -o objs/ut.objs/tests/test_exceptions.o -c tests/test_exceptions.cpp
	@cp objs/ut.objs/tests/test_exceptions.o.dep objs/ut.objs/tests/test_exceptions.o.dep.P; \
    sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\$$//' \
        -e '/^$$/ d' -e 's/$$/ :/' < objs/ut.objs/tests/test_exceptions.o.dep >> objs/ut.objs/tests/test_exceptions.o.dep.P; \
    rm -f objs/ut.objs/tests/test_exceptions.o.dep

-include objs/ut.objs/tests/test_exceptions.o.dep.P


ut: objs/ut.objs/tests/main.o objs/ut.objs/tests/test_mock_scope.o objs/ut.objs/tests/test_traits.o objs/ut.objs/tests/test_exceptions.o Makefile
	$(CXX) -o ut  objs/ut.objs/tests/main.o objs/ut.objs/tests/test_mock_scope.o objs/ut.objs/tests/test_traits.o objs/ut.objs/tests/test_exceptions.o
